facturacion_electronica/apps/factura/urls.py
from apps.factura.views import factura_pdf

__author__ = 'metallica'

from django.conf.urls import include, url

urlpatterns = [
    #Linea comentada para evitar errores de import
    url(r"^factura/pdf/", factura_pdf.as_view()),

    url(r'^factura/historial/', 'apps.factura.views.lista_facturas', name='lista_facturas'),
    url(r'^factura/nueva/', 'apps.factura.views.nueva', name='nueva'),
    url(r'^factura/(?P<factura_id>\d+)/', 'apps.factura.views.detalles_factura', name='detalles_factura'),
    url(r'^correo/(?P<factura_id>\d+)/', 'apps.factura.views.enviar_correo_factura', name='enviar_correo_factura'),

    url(r'^factura/historial_xml/', 'apps.factura.views.detalle_facturas_xml', name='facturas_xml'),
    url(r'^factura/(?P<accion>\w+)/(?P<id_factura>\d+)', 'apps.factura.views.detalle_factura_xml', name='acciones_factura'),



    #url(r'^factura/historial/', 'apps.factura.views.lista_facturas', name='lista_facturas'),

    #url('', include('social.apps.django_app.urls', namespace='social')),

]

facturacion_electronica/apps/index/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'apps.index.views.index', name='index'),
]

facturacion_electronica/apps/usuarios/urls.py
from django.conf.urls import include, url

urlpatterns = [


    url(r'^login/$', 'apps.usuarios.views.logIn', name='login'),
    url(r'^logout/$', 'apps.usuarios.views.logOut', name='logout'),
    #url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^perfil/$', 'apps.usuarios.views.perfil', name='perfil'),


]

facturacion_electronica/facturacion_electronica/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from apps.usuarios.forms import EmailValidationOnForgotPassword


urlpatterns = [
    # Examples:
    # url(r'^$', 'facturacion_electronica.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.index.urls', namespace='index_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^', include('apps.factura.urls', namespace='factura_app')),



    # Urls para re establecer el password
    url(r'^reset/password_reset/$', 'django.contrib.auth.views.password_reset',
        {'password_reset_form': EmailValidationOnForgotPassword}, name='reset_password_reset1'),
    url(r'^reset/password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

    # login with python social auth
    #   url('', include('social.apps.django_app.urls', namespace='social')),


]

facturacion_electronica/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head lang="es-MX">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %} | facturaS</title>

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic|Roboto+Condensed:300italic,400italic,700italic,400,300,700' rel='stylesheet' type='text/css'>
    <link href="{% static 'base/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'base/font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <link href="{% static 'base/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'base/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'base/css/main.css' %}" rel="stylesheet">
    <link href="{% static 'base/css/base.css' %}" rel="stylesheet">

    {% block styles %}
    
    {% endblock %}

    <!--[if gte IE 9]>
        <style type="text/css">
            .gradient {
                filter: none;
            }
        </style>
    <![endif]-->
</head>
<body class="pace-done fixed-nav fixed-sidebar">

<div id="wrapper">

    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav" id="side-menu">
                <li class="nav-header">
                    {% if user.is_authenticated %}
                    <div class="dropdown profile-element text-center">
                        {% if user.get_image != "" %}
                            <img alt="image" class="img-circle center-block" src="{{ user.get_image }}" style="height: 48px; width: 48px"/>
                        {% else %}
                            <img alt="image" class="img-circle center-block" src="{% static 'base/img/avatar.jpg' %}" style="height: 48px; width: 48px"/>
                        {% endif %}
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">{{ nombre }}</strong>
                        </span> <span class="text-muted text-xs block">{{ titulo }} <b class="caret"></b></span> </span> </a>
                    </div>
                    {% endif %}
                    <div class="logo-element">
                        RENKA
                    </div>
                </li>
                <li class="active">
                </li>
                <li >
                    <a href="#"><i class="fa fa-usd"></i> <span class="nav-label">Mis Facturas</span></a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-th-large"></i> <span class="nav-label">Crear</span> </a>
                </li>
            </ul>

        </div>
    </nav>
    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            <nav class="navbar navbar-fixed-top white-bg" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                    <form role="search" class="navbar-form-custom" method="post" action="#">
                        <div class="form-group">
                            <input type="text" placeholder="Buscar..." class="form-control" name="top-search" id="top-search">
                        </div>
                    </form>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#" aria-expanded="false">
                            <i class="fa fa-gear"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-messages">
                            <li><a href="">¿Cómo funciona?</a></li>
                            <li><a href="">Invierte</a></li>
                            <li><a href="{% url 'factura_app:nueva' %}">Sube tu proyecto</a></li>
                        </ul>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <div data-toggle="dropdown" id="menu-profile" class="dropdown-toggle" aria-expanded="true">
                                <span class="m-r-md">{{ user.get_short_name }}</span>
                            {% if user.get_image != "" %}
                                <img alt="image" class="img-circle" src="{{ user.get_image }}" style="height: 42px"/>
                            {% else %}
                                <img alt="image" class="img-circle" src="{% static 'base/img/avatar.jpg' %}" style="height: 42px"/>
                            {% endif %}

                            </div>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="menu-profile">
                                <li><a href="#">Mi Cuenta</a></li>
                                <li><a href="{% url 'usuarios_app:editar_perfil' %}">Editar Perfil</a></li>
                                <li><a href="#">Configuración</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Salir</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="{% url 'usuarios_app:logout' %}">
                                <i class="fa fa-sign-out"></i> Salir
                            </a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'usuarios_app:login' %}">
                                <i class="fa fa-sign-in"></i> Ingresar
                            </a>
                        </li>
                    {% endif %}
                </ul>

            </nav>
x|        </div>

        <div class="wrapper wrapper-content">
            <div class="container-fluid">
                {% block content %}

                {% endblock %}
            </div>
        </div>

        <div class="footer">
            <div class="pull-right">
                <a href="#">Términos y Condiciones</a>
            </div>
            <div>
                <strong>Copyright</strong> Renka © {% now "Y" %}
            </div>
        </div>

        {% comment %}<div class="row foot">
            <div class="col-sm-1">
                <a class="footer-logo hidden-xs" href="#"><img class="img-responsive" src="{% static 'base/img/logo-renka-outline.png' %}" alt=""/></a>
            </div>
            <div class="col-sm-4">
                <p class="footer-title">ACERCA DE RENKA</p>
                <ul>
                    <li>¿Qué es Renka?</li>
                    <li>¿Quiénes somos?</li>
                    <li>Proyectos</li>
                    <li>Proyectos que Recomendamos</li>
                    <li>Ayuda</li>
                </ul>
            </div>
            <div class="col-sm-3">
                <p class="footer-title">FAQ</p>
                <ul>
                    <li>Soporte</li>
                    <li>Términos y Condiciones</li>
                    <li>Políticas de Privacidad</li>
                </ul>
            </div>
            <div class="col-sm-4">
                <p class="footer-title">CONTACTO</p>
                <ul>
                    <li><i class="fa fa-facebook"></i>/somosrenka</li>
                    <li><i class="fa fa-twitter"></i>@somosrenka</li>
                </ul>
                <p class="footer-title">Teléfono</p>
                <ul>
                    <li>55 2345-2316</li>
                </ul>
                <p class="footer-title">Dirección</p>
                <ul>
                    <li>Calle Lago Alberto 320, Miguel Hidalgo, Anáhuac, 11320 Ciudad de México, D.F.</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 footer-brand-col">

            </div>
        </div>
        {% endcomment %}
    </div>
</div>


<!-- Mainly scripts -->
<script src="{% static 'base/js/jquery-2.1.1.js' %}"></script>
<script src="{% static 'base/js/bootstrap.min.js' %}"></script>
<script src="{% static 'base/js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
<script src="{% static 'base/js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

<script src="{% static 'base/js/plugins/chartJs/Chart.min.js' %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static 'base/js/inspinia.js' %}"></script>
<script src="{% static 'base/js/plugins/pace/pace.min.js' %}"></script>

<!-- Flot -->
<script src="{% static 'base/js/plugins/flot/jquery.flot.js' %}"></script>
<script src="{% static 'base/js/plugins/flot/jquery.flot.tooltip.min.js' %}"></script>
<script src="{% static 'base/js/plugins/flot/jquery.flot.resize.js' %}"></script>

{% block scripts %}

{% endblock %}


</body>
</html>

facturacion_electronica/templates/base/base_no_sidebar.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head lang="es-MX">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %} Factura </title>

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic|Roboto+Condensed:300italic,400italic,700italic,400,300,700'
          rel='stylesheet' type='text/css'>
    <link href="{% static 'base/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'base/font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <link href="{% static 'base/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'base/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'base/css/main.css' %}" rel="stylesheet">
    <link href="{% static 'base/css/base.css' %}" rel="stylesheet">

    {% block styles %}

    {% endblock %}

    <!--[if gte IE 9]>
        <style type="text/css">
            .gradient {
                filter: none;
            }
        </style>
    <![endif]-->
</head>

<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
<body class="top-navigation">

<div id="wrapper">
    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom white-bg">
            <nav class="navbar navbar-static-top" role="navigation">
                <div class="navbar-header">
                    <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse"
                            class="navbar-toggle collapsed" type="button">
                        <i class="fa fa-reorder"></i>
                    </button>
                    <a href="{% url 'index_app:index' %}" class="navbar-brand">
                        <img src="{% static 'base/img/logo-renka-dark.png' %}" alt=""/>MyFac
                    </a>
                </div>
                <div class="navbar-collapse collapse" id="navbar">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#"> Inicio </a>
                        </li>
                        <li>
                            <a href="{% url 'factura_app:nueva' %}"> crea tu factura </a>
                        </li>
                    </ul>
                    <ul class="nav navbar-top-links navbar-right">
                        {% if user.is_authenticated %}
                            <li>
                                <div data-toggle="dropdown" id="menu-profile" class="dropdown-toggle"
                                     aria-expanded="true">
                                    <ul>
                                        <li>
                                            <span class="m-r-md" href="#">{{ user.get_short_name }}</span>
                                        </li>
                                        <li>
                                            {% if user.get_image != "" %}
                                                <div class="avatar img-circle img-user">
                                                    <style>
                                                        .img-user {
                                                            position: relative;
                                                            top: 10px;
                                                            background-image: url({{ user.get_image }});
                                                            width: 36px !important;
                                                            margin-right: 5px;
                                                            padding-bottom: 36px;
                                                        }
                                                    </style>
                                                </div>
                                            {% else %}
                                                <img alt="image" class="img-circle"
                                                     src="{% static 'base/img/avatar.jpg' %}"/>
                                            {% endif %}
                                        </li>
                                    </ul>
                                </div>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="menu-profile">
                                    <li><a href="{% url 'factura_app:lista_facturas' %}">Mis Facturas</a></li>
                                    <li><a href="{% url 'usuarios_app:perfil' %}">Editar Perfil</a></li>
                                    <li class="divider"></li>
                                    <li><a href="/logout">Salir</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="{% url 'usuarios_app:logout' %}">
                                    <i class="fa fa-sign-out"></i> Salir
                                </a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'usuarios_app:login' %}">
                                    <i class="fa fa-sign-in"></i> Ingresar
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
        <div class="wrapper wrapper-content">
            <div class="container">
                {% block content %}

                {% endblock %}
            </div>
        </div>
        <div class="footer">
            <div class="pull-right">
                <strong>Términos y Condiciones</strong>
            </div>
            <div>
                <strong>Copyright</strong> MyFac © {% now "Y" %}
            </div>
        </div>
    </div>
</div>

<!-- Mainly scripts -->
<script src="{% static 'base/js/jquery-2.1.1.js' %}"></script>
<script src="{% static 'base/js/bootstrap.min.js' %}"></script>
<script src="{% static 'base/js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
<script src="{% static 'base/js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

<script src="{% static 'base/js/plugins/chartJs/Chart.min.js' %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static 'base/js/inspinia.js' %}"></script>
<script src="{% static 'base/js/plugins/pace/pace.min.js' %}"></script>

<!-- Flot -->
<script src="{% static 'base/js/plugins/flot/jquery.flot.js' %}"></script>
<script src="{% static 'base/js/plugins/flot/jquery.flot.tooltip.min.js' %}"></script>
<script src="{% static 'base/js/plugins/flot/jquery.flot.resize.js' %}"></script>

<script src="{% static 'base/js/plugins/jquery.number.min.js' %}"></script>

{% block scripts %}

{% endblock %}

</body>
</html>