facturacion_electronica/apps/factura/urls.py
from apps.factura.views import factura_pdf

__author__ = 'metallica'

from django.conf.urls import include, url

urlpatterns = [
    #Linea comentada para evitar errores de import
    url(r"^factura/pdf/", factura_pdf.as_view()),

    url(r'^factura/historial/', 'apps.factura.views.lista_facturas', name='lista_facturas'),
    url(r'^factura/nueva/', 'apps.factura.views.nueva', name='nueva'),
    url(r'^factura/(?P<factura_id>\d+)/', 'apps.factura.views.detalles_factura', name='detalles_factura'),
    url(r'^correo/(?P<factura_id>\d+)/', 'apps.factura.views.enviar_correo_factura', name='enviar_correo_factura'),

    url(r'^factura/historial_xml/', 'apps.factura.views.detalle_facturas_xml', name='facturas_xml'),
    url(r'^factura/(?P<accion>\w+)/(?P<id_factura>\d+)', 'apps.factura.views.detalle_factura_xml', name='acciones_factura'),



    #url(r'^factura/historial/', 'apps.factura.views.lista_facturas', name='lista_facturas'),

    #url('', include('social.apps.django_app.urls', namespace='social')),

]

facturacion_electronica/apps/usuarios/urls.py
from django.conf.urls import include, url

urlpatterns = [


    url(r'^login/$', 'apps.usuarios.views.logIn', name='login'),
    url(r'^logout/$', 'apps.usuarios.views.logOut', name='logout'),
    #url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^perfil/$', 'apps.usuarios.views.perfil', name='perfil'),


]

facturacion_electronica/facturacion_electronica/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from apps.usuarios.forms import EmailValidationOnForgotPassword


urlpatterns = [
    # Examples:
    # url(r'^$', 'facturacion_electronica.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.index.urls', namespace='index_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^', include('apps.factura.urls', namespace='factura_app')),



    # Urls para re establecer el password
    url(r'^reset/password_reset/$', 'django.contrib.auth.views.password_reset',
        {'password_reset_form': EmailValidationOnForgotPassword}, name='reset_password_reset1'),
    url(r'^reset/password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

    # login with python social auth
    #   url('', include('social.apps.django_app.urls', namespace='social')),


]

facturacion_electronica/apps/factura/models.py
#enconding: utf-8

from django.db import models
from apps.usuarios.models import Usuario
from django.utils.datetime_safe import *
from easymode.tree.decorators import toxml


# Create your models here.

@toxml
class Factura (models.Model):
    nombre = models.CharField(max_length=40)
    usuario = models.ForeignKey(Usuario)
    fecha = models.DateField(default=datetime.now)
    status = models.BooleanField(default=False)  #
    importe = models.FloatField(default=0.0)
    descripcion = models.CharField(max_length=300)







    def __str__(self):
        return str(self.nombre + ": " + self.usuario.nombres)

facturacion_electronica/apps/factura/forms.py
#enconding: utf-8
__author__ = 'metallica'
from apps.factura.models import Factura
from django import forms




class facturaForm(forms.ModelForm):
    class Meta:
        model = Factura
        fields = ('nombre', 'importe','descripcion')
        widgets = {
            'nombre': forms.TextInput(attrs={
                'placeholder': 'Nombre de la factura',
                'class': 'form-control',
            }),
            'importe': forms.TextInput(attrs={
                'placeholder': 'importe',
                'class': 'form-control',
            }),
            'descripcion': forms.Textarea(attrs={
                'type': 'text',
                'placeholder': 'descripcion de la operacion',
                'class': 'form-control psw',
            }),
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        return cleaned_data

facturacion_electronica/apps/factura/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from easymode.tree import xml
from apps.factura.forms import facturaForm
from apps.factura.models import Factura
from django.contrib.auth.decorators import login_required


def nueva(request):
    if not request.user.is_authenticated():
        return redirect('/login')
    nueva_factura = facturaForm()
    if request.method == 'POST':
        if 'factura_form' in request.POST:
            nueva_factura = facturaForm(request.POST)
            if nueva_factura.is_valid():
                print("form valida")
                factura= Factura.objects.create(usuario=request.user,
                                                nombre=nueva_factura.cleaned_data['nombre'].lower().strip(),
                                                importe=nueva_factura.cleaned_data['importe'],
                                                descripcion=nueva_factura.cleaned_data['descripcion'].strip(),
                                                )
            exito = 'Agregaste con exito una factura :D'
            return render(request, 'factura/nueva.html', {'exito': exito,'nueva_factura':facturaForm()})

    return render(request, 'factura/nueva.html', {'nueva_factura': nueva_factura,'exito':'',})



def lista_facturas(request):
    if not request.user.is_authenticated():
        return redirect('/login')
    lista_facturas = Factura.objects.filter(usuario=request.user)
    exito=''
    return render(request, 'factura/lista_facturas.html', {'exito': exito,'lista_facturas':lista_facturas })


def detalles_factura(request,factura_id):
    if not request.user.is_authenticated():
        return redirect('/login')
    factura = get_object_or_404(Factura, pk=factura_id)
    extra=1
    return render(request, 'factura/detalle_factura.html', {'factura': factura,
                                                           'extra':extra,
                                                           })

from yattag import Doc, indent
from django.utils.encoding import smart_str

def detalle_facturas_xml(request):
    from django.http import HttpResponse
    from django.core.servers.basehttp import FileWrapper
    # generate the file
    facturas = Factura.objects.filter(usuario=request.user)

    factura_xml = crear_xml(request.user, facturas)
    nombre_archivo= 'media/xml/'+str(request.user)+'_facturas.xml'
    archivo = open(nombre_archivo,'w')
    archivo.write(factura_xml)
    print(factura_xml)
    #'''
    response = HttpResponse(factura_xml, content_type='application/xml')
    response['Content-Disposition'] = 'attachment; filename='+nombre_archivo
    #archivo.close()
    return response

    '''
    print(factura_xml)
    response = HttpResponse(content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(nombre_archivo)
    response['X-Sendfile'] = smart_str(archivo)
    # It's usually a good idea to set the 'Content-Length' header too.
    # You can also set any other required headers: Cache-Control, etc.
    return response
    '''


def detalle_factura_xml(request, accion ,id_factura):
    from django.http import HttpResponse
    from django.core.servers.basehttp import FileWrapper
    # generate the file
    if accion=='xml':
        try:
            fac = Factura.objects.get (id=id_factura)
            if fac:
                factura = crear_xml_factura(fac,id_factura)
                nombre_archivo= 'media/xml/'+str(request.user.username)+'-factura_'+str(id_factura)+'.xml'
                archivo = open(nombre_archivo,'w')
                archivo.write(factura)
                print(factura)
                #'''
                response = HttpResponse(factura, content_type='application/xml')
                response['Content-Disposition'] = 'attachment; filename='+nombre_archivo.split('/')[-1]
                #archivo.close()
                return response

            lista_facturas = Factura.objects.filter(usuario=request.user)
            exito=''
            return render(request, 'factura/lista_facturas.html', {'exito': exito,'lista_facturas':lista_facturas })

        except Exception as e:
            print (e)
            lista_facturas = Factura.objects.filter(usuario=request.user)
            exito=''
            return render(request, 'factura/lista_facturas.html', {'exito': exito,'lista_facturas':lista_facturas })

    elif accion=='borrar':
        try:
            factura = Factura.objects.filter(id=id_factura)
            if factura:
                factura.delete()
                print('se elimino la factura')

                lista_facturas = Factura.objects.filter(usuario=request.user)
                exito=''
                return render(request, 'factura/lista_facturas.html', {'exito': exito,'lista_facturas':lista_facturas })
            lista_facturas = Factura.objects.filter(usuario=request.user)
            exito=''
            return render(request, 'factura/lista_facturas.html', {'exito': exito,'lista_facturas':lista_facturas })
        except:
            lista_facturas = Factura.objects.filter(usuario=request.user)
            exito=''
            return render(request, 'factura/lista_facturas.html', {'exito': exito,'lista_facturas':lista_facturas })

def crear_xml(usuario, facturas):
    doc, tag, text = Doc().tagtext()

    with tag('Usuario',name=usuario.username):
        with tag('Informacion_Personal'):
            with tag('nombre'):
                text(usuario.nombres)
            with tag('Apellidos'):
                text(usuario.apellidos)
            with tag('email'):
                text(usuario.email)
            with tag('RFC'):
                text(usuario.rfc)
            with tag('Telefono'):
                text(usuario.telefono)
            with tag('Direccion'):
                text(usuario.direccion)
        if facturas:
            with tag('Facturas'):
                for factura in facturas:
                    with tag('Factura', id=str(factura.id)):
                        with tag('Nombre'):
                            text(factura.nombre)
                        with tag('fecha'):
                            text(str(factura.fecha))
                        with tag('descripcion'):
                            text(factura.descripcion)
                        with tag('importe'):
                            text(str(factura.importe))

    result = indent(
        doc.getvalue(),
        indentation = ' '*4,
        newline = '\r\n'
    )

    return result

##########
def crear_xml_factura(factura,id_factura):
    doc, tag, text = Doc().tagtext()

    with tag('Factura', id=str(id_factura)):
        with tag('Nombre'):
            text(factura.nombre)
        with tag('fecha'):
            text(str(factura.fecha))
        with tag('descripcion'):
            text(factura.descripcion)
        with tag('importe'):
            text(str(factura.importe))

    result = indent(
        doc.getvalue(),
        indentation = ' '*4,
        newline = '\r\n'
    )

    return result

def enviar_correo_factura(request,factura_id):
    if not request.user.is_authenticated():
        return redirect('/login')
    factura = get_object_or_404(Factura, pk=factura_id)
    extra=1
    return render(request, 'factura/envio_correo_exito.html', {'factura': factura,
                                                           'extra':extra,
                                                           })


#'''
from easy_pdf.views import PDFTemplateView
class factura_pdf(PDFTemplateView):
    #template_name = "factura/lista_facturas.html"
    #template_name = "usuarios/perfil.html"
    template_name = "factura/../../templates/factura/factura_pdf.html"
#'''

facturacion_electronica/templates/factura/detalle_factura.html
{% extends 'base/base_no_sidebar.html' %}
{% block title %}
    Detalle factura
{% endblock %}

{% block content %}
    <h2>Descripcion detallada ...</h2>
        <div class="col-md-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Factura {{ factura.id }}</h5>
                </div>
                <div>
                    <div class="ibox-content profile-content" >
                        <div id="div_usuario">
                            <h4><strong>{{ factura.nombre }}</strong></h4>
                            <p>Fecha: {{ factura.fecha }}</p>
                            <p>Importe: {{ factura.importe }}</p>
                            <p>Descripcion: {{ factura.descripcion }}</p>
                            <p>RFC: {{ user.rfc }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

facturacion_electronica/templates/factura/envio_correo_exito.html
{% extends 'base/base_no_sidebar.html' %}
{% load staticfiles %}
{% load humanize %}

{% block title %}
    Envio exitoso
{% endblock %}


{% block styles %}
    <link rel="stylesheet" href="{% static '' %}"/>
{% endblock %}


{% block content %}
    <div class="row row-centered">
        <div class="col-xs-12 text-center">
            <div class="alert alert-success">
                <h2>Se ah enviado con exito una copia de la factura a tu correo !</h2>
            </div>
        </div>
        <h3>Puedes seguir creando y administrando tus facturas o completar tu perfil para agilizar la creacion de facturas</h3>
        <div class="col-xs-3 col-centered m-t-xl">
            <a href="{% url 'factura_app:nueva' %}" class="btn btn-info btn-block">Crear una factura</a>
        </div>
        <div class="col-xs-3 col-centered m-t-xl">
            <a href="{% url 'usuarios_app:perfil' %}" class="btn btn-success btn-block">Ir a mi perfil</a>
        </div>
    </div>
{% endblock %}


{% block scripts %}

{% endblock %}

facturacion_electronica/templates/factura/factura_pdf.html
{% extends "easy_pdf/base.html" %}

{% block layout_style %}
    <style type="text/css">
        @page {
            size: {{ pagesize|default:"A4" }};
            margin-left: 5.5cm;
            margin-right: 2.5cm;
            margin-top: 2.5cm;
            margin-bottom: 2cm;
            @frame header {
                -pdf-frame-content: page-header;
                margin-top: 1.3cm;
                margin-right: 2mm;
                margin-bottom: 1cm;
                margin-left: 1.2cm;
            }
        }
    </style>
{% endblock %}

{% block extra_style %}
    <style type="text/css">
        @font-face { font-family: Lato; src: url(fonts/Lato-Bol.ttf); font-weight: bold; }
        @font-face { font-family: Lato; src: url(fonts/Lato-Reg.ttf); }
        @font-face { font-family: "Lato Light"; src: url(fonts/Lato-Lig.ttf); }
        html {
            font-family: "Lato", "Helvetica", "sans-serif";
            color: #333333;
        }
        p {
            margin: 0 0 6px 0;
            font-size: 11pt;
            font-family: "Lato", "Helvetica", "sans-serif";
        }
        table {
            line-height: 140%;
            margin-bottom: 20px;
        }
            table.bordered {
                border-top: 0.1pt solid #999999;
                border-bottom: 0.1pt solid #999999;
            }
            tr, td, th { border: none; }
            th {
                font-size: 10pt;
                border-bottom: 0.1pt solid #999999;
                padding: 3px 0;
                line-height: 1;
                font-weight: bold;
            }
            td {
                font-size: 10pt;
                font-family: "Lato", "Helvetica", "sans-serif";
                vertical-align: top;
                padding: 3px 0;
            }
            td:last-child { padding-bottom: 0; }
        .text-left { text-align: left; }
        .text-right { text-align: right; }
        .bottom-10 { margin-bottom: 10px; }
        .bottom-20 { margin-bottom: 20px; }
        .header { color: #7f7f7f; }
        .header p { font-size: 13px; line-height: 1.5em; }
        .header-link { font-weight: bold; text-decoration: none; color: #4F81BD; font-size: 14px; }
        .logo { margin-bottom: 20px; margin-left: -25px; }
        .logo img { zoom: 60%; }
        .recipient { margin-left: 7cm; }
        .main h1 {
            margin: 18px 0 18px 0;
            font-size: 250%;
            font-weight: normal;
            color: #4F81BD;
        }
        .main h2 {
            margin: 18px 0 6px 0;
            font-size: 180%;
            font-weight: normal;
        }
        .info { border: 1px solid #4F81BD; padding: 10px; margin-top: 50px; margin-bottom: 50px; }
        .info a { color: #4F81BD; text-decoration: none; }
    </style>
{% endblock %}

{%block page_header%}
    <div id="page-header">
        <div class="header">
            <p class="logo"><img src="img/logo.jpg" /></p>
            <p>
                Street Name <br>
                Postal Code <br/>
                City
            </p>
            <p class="header-link">
                <a class="header-link" href="http://en.ig.ma/">en.ig.ma</a>
            </p>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div id="content">
        <div class="recipient bottom-10">
            <p class="bottom-10">
                <strong>ACME Inc.</strong>
                <br> John Doe
            </p>
            <p class="bottom-10">
                Street Name <br>
                Postal Code <br/>
                City
            </p>
            <p>{{ today|date:"DATETIME_FORMAT" }} UTC</p>
        </div>


        <p class="info">
            This is an example of <a href="https://github.com/nigma/django-easy-pdf">django-easy-pdf</a>
            &ndash; Django PDF rendering the easy way.
            Check <a href="http://en.ig.ma/">en.ig.ma</a> for Django and Python development.
        </p>

        <div class="main">
            <h1>Sample Invoice</h1>

            <table class="bordered bottom-20">
                <tr>
                    <td class="item-name"><strong>Invoice number</strong></td>
                    <td><strong>{{ today|date:"y/m/d/1" }}</strong></td>
                </tr>
                <tr>
                    <td class="item-name">Amount</td>
                    <td><strong>100 Doge</strong></td>
                </tr>
            </table>

            <table>
                <thead>
                    <tr>
                        <th class="text-left">Description</th>
                        <th class="text-right">Amount</th>
                        <th class="text-right">Tax</th>
                        <th class="text-right">Total</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="text-left">Some stuff</td>
                        <td class="text-right">100 Doge</td>
                        <td class="text-right">0</td>
                        <td class="text-right">100 Doge</td>
                    </tr>
                </tbody>
            </table>

            <table class="bottom-20">
                <tr>
                    <td><strong>Total</strong></td>
                    <td class="text-right"><strong>100 Doge</strong></td>
                </tr>
            </table>

            <h2>Payment details</h2>

            <p class="bottom-20">
                Please cover the invoice within 10 days.
            </p>

            <p>Dogecoin address (it's real): <strong>DREWeqR5KB2rbpJFybKvWepNs6sUQZowNs</strong></p>
            <pdf:barcode value="DREWeqR5KB2rbpJFybKvWepNs6sUQZowNs" type="qr" barwidth="100" barheight="100" />
        </div>
    </div>
{% endblock %}

facturacion_electronica/templates/factura/lista_facturas.html
{% extends 'base/base_no_sidebar.html' %}
{% block title %}
    HISTORIAL
{% endblock %}

{% block content %}
        <a class="btn btn-primary m-b pull-right" href="{% url 'factura_app:facturas_xml' %}">XML</a>

    <span><h2><strong> Mis Facturas </strong></h2></span>
    <br><br>

    {% if lista_facturas != '' %}

        {% for factura in lista_facturas %}
            <div class="col-md-4">
                <div class="ibox float-e-margins">
                        <br><strong><a style="text-align:left"  href="{% url 'factura_app:acciones_factura' 'borrar'  factura.id %}">eliminar</a></strong>
                    <div class="ibox-title">
                        <h5><strong>{{ factura.nombre }}</strong></h5>

                    </div>
                    <div>
                        <div class="ibox-content profile-content">
                            <div id="div_usuario">

                                <p>Fecha: {{ factura.fecha }}</p>

                                <p>Importe: {{ factura.importe }}</p>

                                <p>Descripcion: {{ factura.descripcion }}</p>

                                <p>RFC: {{ user.rfc }}</p>
                                <a href="{% url 'factura_app:detalles_factura'  factura.id %}">Ver mas...</a><br>
                                <a href="{% url 'factura_app:acciones_factura' 'xml'  factura.id %}">xml</a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        {% endfor %}



    {% else %}
        <br>
        <h3> Aun no has creado ninguna factura :( </h3>


    {% endif %}


{% endblock %}

facturacion_electronica/templates/factura/nueva.html
{% extends 'base/base_no_sidebar.html' %}

{% block title %}
    Nueva
{% endblock %}


{% block content %}

    <span>VISTA PARA CREAR UNA FACTURA NUEVA</span>
            {% if exito != '' %}
                    <h3 style="color: #b94a48">{{ exito }}</h3>
            {% endif %}
                <form role="form" method="post" accept-charset="utf-8">
                    {% csrf_token %}

                    {% for field in nueva_factura %}
                        <div class="form-group">
                            <!-- Render the field label tag -->
                                {{ field }}
                            <!--  muestra los errores que halla en los fields -->
                            {% if field.errors %}
                                <p class="error">
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                                </p>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button class="btn btn-primary m-b pull-right" id="btn-submit" type="submit" name="factura_form">crear factura</button>
                </form>

{% endblock %}