facturacion_electronica/apps/usuarios/urls.py
from django.conf.urls import include, url

urlpatterns = [


    url(r'^login/$', 'apps.usuarios.views.logIn', name='login'),
    url(r'^logout/$', 'apps.usuarios.views.logOut', name='logout'),
    #url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^perfil/$', 'apps.usuarios.views.perfil', name='perfil'),


]

facturacion_electronica/facturacion_electronica/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from apps.usuarios.forms import EmailValidationOnForgotPassword


urlpatterns = [
    # Examples:
    # url(r'^$', 'facturacion_electronica.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.index.urls', namespace='index_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^', include('apps.factura.urls', namespace='factura_app')),



    # Urls para re establecer el password
    url(r'^reset/password_reset/$', 'django.contrib.auth.views.password_reset',
        {'password_reset_form': EmailValidationOnForgotPassword}, name='reset_password_reset1'),
    url(r'^reset/password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

    # login with python social auth
    #   url('', include('social.apps.django_app.urls', namespace='social')),


]

facturacion_electronica/apps/usuarios/models.py
#enconding: utf-8

from django.db import models
from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils.datetime_safe import *

# Create your models here.
class UserManager(BaseUserManager, models.Manager):
    def _create_user(self, username, email, password, is_staff,
                     is_superuser, **extra_fields):
        email = self.normalize_email(email)
        # TWITTER Y LINKEDIN NO NOS DAN  el email del usuario, cpor estas dos lineas truena
        # if not email:
        # raise ValueError('El email debe ser obligatorio')
        user = self.model(username=username, email=email, is_active=True,
                          is_staff=is_staff, is_superuser=is_superuser, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, password=None, **extra_fields):
        return self._create_user(username, email, password, False,
                                 False, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        return self._create_user(username, email, password, True,
                                 True, **extra_fields)


class Usuario(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=20, unique=True)
    nombres = models.CharField(max_length=40)
    apellidos = models.CharField(max_length=40)
    fechaRegistro = models.DateField(default=datetime.now)
    email = models.EmailField()
    status = models.BooleanField(default=False)  # para verificar si ya hemos registrado al usuario o no con nosotros
    avatar = models.URLField(blank=True)  # necesario para captar la imagen  de perfil de su red social

    rfc = models.CharField(max_length=18)
    telefono = models.CharField(max_length=10)
    direccion= models.CharField(max_length=80)

    # Los siguientes 2 campos son requeridos para un modelo de usuarios
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    @property
    def get_short_name(self):
        if self.nombres != "":
            return self.nombres
        elif self.username != "":
            return self.username
        else:
            return self.email

    @property
    def get_full_name(self):
        if self.nombres != "":
            return self.nombres + " " + self.apellidos
        elif self.username != "":
            return self.username
        else:
            return self.email

    @property
    def get_image(self):
        return self.avatar

    def __str__(self):
        return str(self.nombres + "_" + self.username)

class persona_moral(models.Model):
    usuario= models.ForeignKey(Usuario)




class EmailOrUsernameModelBackend(ModelBackend):
    def authenticate(self, username=None, password=None):
        if '@' in username:
            kwargs = {'email': username}
        else:
            kwargs = {'username': username}
        try:
            user = Usuario.objects.get(**kwargs)
            if user.check_password(password):
                return user
        except Usuario.DoesNotExist:
            return None

    def get_user(self, username):
        try:
            return Usuario.objects.get(pk=username)
        except Usuario.DoesNotExist:
            return None

    def __str__(self):
        return str(self)

facturacion_electronica/apps/usuarios/forms.py
# -*- encoding: utf-8 -*-
from django.forms import ModelForm

__author__ = 'metallica'

from django import forms
from django.conf import settings
from django.contrib.auth.forms import PasswordResetForm
from django.core.exceptions import ValidationError

from .models import Usuario


'''
                <div>
                    <a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}" class="btn btn-success btn-twitter ">
                        <i class="fa fa-twitter"> </i>
                    </a>
                    <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}" class="btn btn-success btn-facebook ">
                        <i class="fa fa-facebook"> </i>
                    </a>
                    <a href="{% url 'social:begin' 'google-plus' %}?next={{ request.path }}" class="btn btn-success btn-google-plus ">
                        <i class="fa fa-google-plus"> </i>
                    </a>
                    <a href="{% url 'social:begin' 'linkedin' %}?next={{ request.path }}" class="btn btn-success btn-linkedin ">
                        <i class="fa fa-linkedin"> </i>
                    </a>
                    <br>
                </div>

'''
class LoginForm(forms.Form):
    username = forms.CharField(max_length=50,
                               widget=forms.TextInput(attrs={
                                   'placeholder': 'Nombre de Usuario/Email',
                                   'class': 'form-control',
                               }))
    password = forms.CharField(max_length=50,
                               widget=forms.TextInput(attrs={
                                   'type': 'password',
                                   'placeholder': 'Password',
                                   'class': 'form-control',
                               }))

    recordarme = forms.BooleanField(required=False,
                                    widget=forms.CheckboxInput())

    def clean(self):
        cleaned_data = self.cleaned_data
        print ("selfcleaned data : ", (self.cleaned_data))
        recordarme = self.cleaned_data.get('recordarme')
        print ("recordarme = ", recordarme)
        if not recordarme:
            settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = True
        else:
            settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False
        return cleaned_data

class completar_perfil_form(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('nombres', 'apellidos', 'email','rfc','telefono','direccion')
        widgets = {
            'nombres': forms.TextInput(attrs={
                'placeholder': 'Nombre de Usuario',
                'class': 'form-control',
            }),
            'apellidos': forms.TextInput(attrs={
                'type': 'text',
                'placeholder': 'Apellidos ..',
                'class': 'form-control',
            }),
            'email': forms.TextInput(attrs={
                'type': 'email',
                'placeholder': 'correo electronico',
                'class': 'form-control psw',
            }),
            'rfc': forms.TextInput(attrs={
                'type': 'text',
                'placeholder': 'tu RFC ',
                'class': 'form-control psw',
            }),
            'telefono': forms.TextInput(attrs={
                'type': 'text',
                'placeholder': 'Tu telefono de contacto',
                'class': 'form-control psw',
            }),
            'direccion': forms.TextInput(attrs={
                'type': 'text',
                'placeholder': 'Direccion completa ...',
                'class': 'form-control psw',
            }),
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        print(cleaned_data)
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(completar_perfil_form, self).__init__(*args, **kwargs)
        #self.fields['username'].required = True
        self.fields['email'].type = 'email'
        self.fields['email'].required = False
        self.fields['nombres'].required = False
        self.fields['apellidos'].required = False
        self.fields['rfc'].required = False
        self.fields['telefono'].required = False
        self.fields['direccion'].required = False



class SignUpForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password')
        widgets = {
            'username': forms.TextInput(attrs={
                'placeholder': 'Nombre de Usuario',
                'class': 'form-control',
            }),
            'email': forms.TextInput(attrs={
                'type': 'email',
                'placeholder': 'Email',
                'class': 'form-control',
            }),
            'password': forms.TextInput(attrs={
                'type': 'password',
                'placeholder': 'password',
                'class': 'form-control psw',
            }),
        }

    def clean(self):
        cleaned_data = self.cleaned_data

        # if len(cleaned_data.get("username")) < 6:
        #     raise forms.ValidationError("El nombre de usuario debe contener mínimo 6 caracteres")
        # if len(cleaned_data.get("password")) < 6:
        #     raise forms.ValidationError("El password debe contener mínimo 6 caracteres")

        if Usuario.objects.filter(username=cleaned_data.get("username").lower()):
            print ("El nombre de usuario ya esta en uso")
            raise forms.ValidationError("El nombre de usuario ya esta en uso...")
        elif Usuario.objects.filter(username=cleaned_data.get("email").lower()):
            print ("El email ya esta en uso...")
            raise forms.ValidationError("El email ya esta en uso...")
        return cleaned_data


class EmailValidationOnForgotPassword(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        if not Usuario.objects.filter(email__iexact=email, is_active=True).exists():
            raise ValidationError("No tenemos tu correo registrado ! D= ")

        return email

facturacion_electronica/apps/usuarios/views.py
# -*- encoding: utf-8 -*-
from django.core.mail import EmailMessage

from django.http import JsonResponse
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import login, logout
from django.views.generic import View, TemplateView
from .forms import LoginForm, SignUpForm, completar_perfil_form
from .models import Usuario, EmailOrUsernameModelBackend
from django.contrib.auth.decorators import login_required
from django.core import serializers


# Create your views here.                                                          'lista_facturas':lista_facturas })

@login_required

def perfil(request):
    #user_register = SignUpForm()
    datos_usuario=1
    if request.method == 'POST':
        completar_perfil = completar_perfil_form(request.POST)
        if completar_perfil.is_valid():
            guardar_informacion(request,completar_perfil)
            return redirect('/factura/nueva')

        return render(request, 'usuarios/perfil.html', {'datos_usuario': datos_usuario,
                                                        'completar_perfil': completar_perfil_form()})

    return render(request, 'usuarios/perfil.html', {'datos_usuario': datos_usuario,
                                                    'completar_perfil':completar_perfil_form()})


def guardar_informacion(request, new_profile):
    if new_profile.cleaned_data['nombres']:
        try:
            request.user.nombres = new_profile.cleaned_data['nombres']
        except:
            pass
    if new_profile.cleaned_data['apellidos']:
        try:
            request.user.apellidos = new_profile.cleaned_data['apellidos']
        except:
            pass
    if new_profile.cleaned_data['rfc']:
        try:
            request.user.rfc = new_profile.cleaned_data['rfc']
        except:
            pass
    if new_profile.cleaned_data['telefono']:
        try:
            request.user.telefono = new_profile.cleaned_data['telefono']
        except:
            pass
    if new_profile.cleaned_data['direccion']:
        try:
            request.user.direccion = new_profile.cleaned_data['direccion']
        except:
            pass
    request.user.save()
    print('guardamos')




def logIn(request):
    user_register = SignUpForm()
    login_form = LoginForm()
    if request.user.is_authenticated():
        return redirect('/factura/nueva')
    template='usuarios/login.html'
    redireccionar= '/factura/nueva'
    if request.method == 'POST':
        if 'register_form' in request.POST:
            user_register = SignUpForm(request.POST)
            if user_register.is_valid():
                user = Usuario.objects.create_user(
                    username=user_register.cleaned_data['username'].lower().strip(),
                    email=user_register.cleaned_data['email'],
                    password=user_register.cleaned_data['password'])

                try:
                    Email_bienvenido(user)
                except:
                    pass

                #sendEmail(user)
                autentificar = EmailOrUsernameModelBackend()
                user = autentificar.authenticate(username=user_register.cleaned_data['username'].lower().strip(),
                                                 password=user_register.cleaned_data['password'])
                if user is not None:
                    if user.is_active:
                        user.backend = 'django.contrib.auth.backends.ModelBackend'
                        login(request, user)
                        return redirect('/perfil')

        if 'login_form' in request.POST:
            login_form = LoginForm(request.POST)
            if login_form.is_valid():
                autentificar = EmailOrUsernameModelBackend()
                user = autentificar.authenticate(username=login_form.cleaned_data['username'].lower().strip(),
                                                 password=login_form.cleaned_data['password'])
                print(user)
                if user is not None:
                    print(user)
                    if user.is_active:
                        user.backend = 'django.contrib.auth.backends.ModelBackend'
                        login(request, user)
                        return redirect(redireccionar)
                    else:
                        user.is_active = True
                        login(request, user)
                        return render_to_response('index/index.html', context={
                            'desactivado': 'Gracias por volver a activar tu cuenta !! :D '})
                else:
                    return render(request, template, {'user_register': user_register,
                                                                   'login_form': login_form,
                                                                   'Error': "El username o password no son validos"})


    return render(request, template, {'user_register': user_register,
                                                   'login_form': login_form})


def logOut(request):
    logout(request)
    return redirect('/login')

def Email_bienvenido(user):
    # to=[request.user.email]
    msg = EmailMessage(subject='Bienvenido',
                       from_email='carlos.thrashaholic@gmail.com <carlos.thrashaholic@gmail.com>',
                       to=[user.email])
    msg.template_name = 'bienvenida.html'
    #si proporciono un username le enviaremos un correo 'mas personalizado' sino solo la bienvenida

    #'std_content00': '<h1>Hola %s Bienvenido a Somosrenka.com <br> gracias por registrarte' %user.username
    msg.template_content = {
        'std_username': 'Hola '+user.get_short_name,#enviamos el saludo a la persona
    }
    try:
        msg.send()
        ##print("se envio correo de bienvenida")
    except Exception as e :
        pass
        ##print("error : ", e )

facturacion_electronica/templates/usuarios/hello.html
{% extends "easy_pdf/base.html" %}

{% block content %}
    <div id="content">
        <h1>PRUEBA DE PDF USANDO EASY-PDF!</h1>
        <h2> FFDP!</h2>

    </div>
{% endblock %}

facturacion_electronica/templates/usuarios/login.html
{% extends 'base/base_no_sidebar.html' %}
{% load staticfiles %}

{% block title %}
    Registrate | Inicia Sesión
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'usuarios/css/style.css' %}"/>
{#    <link rel="stylesheet" href="{% static 'usuarios/css/strength.css' %}"/>#}
    <link rel="stylesheet" href="{% static 'proyectos/css/custom.css' %}"/>
    <style>
        .wrapper .middle-box {
            margin-top: 0;
            margin-bottom: 40px;
        }
    .psw{
        background:transparent;
        height: 34px;
        -webkit-transition: border .25s linear, color .25s linear;
        -moz-transition: border .25s linear, color .25s linear;
        -o-transition: border .25s linear, color .25s linear;
        transition: border .25s linear, color .25s linear;
        -webkit-backface-visibility: hidden;
        width:100%;
        }
        .psw:focus{
        outline:0;
        }
        .strength_meter{
        background:#fff;
        position: absolute;
        left: 0px;
            top: 194px;
            top: 194px;
        width: 100%;
        height: 34px;
        z-index:-1;
        border-radius:5px;
        padding-right:13px;
        }
        .button_strength {
        text-decoration: none;
        font-size: 24px;
        }
        .strength_meter div{
            width:0%;
        height: 34px;
        text-align: right;
        color: #000;
        line-height: 34px;
        -webkit-transition: all .3s ease-in-out;
        -moz-transition: all .3s ease-in-out;
        -o-transition: all .3s ease-in-out;
        -ms-transition: all .3s ease-in-out;
        transition: all .3s ease-in-out;
        padding-right: 12px;
        border-radius:5px;
        }
        .strength_meter div p{
        position: absolute;
        top: 22px;
        right: 0px;
        color: #FFF;
        font-size:13px;
        }

        .veryweak{
            background-color: #FFA0A0;
        border-color: #F04040!important;
        width:25%!important;
        }
        .weak{
        background-color: #FFB78C;
        border-color: #FF853C!important;
        width:50%!important;
        }
        .medium{
        background-color: #FFEC8B;
        border-color: #FC0!important;
        width:75%!important;
        }
        .strong{
        background-color: #C3FF88;
        border-color: #8DFF1C!important;
        width:100%!important;
        }

    </style>
{% endblock %}

{% block content %}

{% if user and not user.is_anonymous and not user.email %}
    <h2> Solo resta que nos proporciones un email para que podamos enviarte informacion...etc</h2>
                <form role="form" method="post" accept-charset="utf-8">
                    {% csrf_token %}
                        <input class="form-control" id="id_email" maxlength="254" name="email" placeholder="Email" type="email">
                    <button class="btn btn-primary m-b pull-right" id="btn-submit" type="submit" name="email_twitter">Registrate</button>
                </form>

{% elif user and not user.is_anonymous and user.email %}
    <div class="row m-lg">
        <div class="col-xs-12">
            <div class="animated fadeInDown">
                <h1>Hola,<br>{{ user.get_short_name }}!</h1>
                <br>
                <h2><a href="/logout">Salir</a></h2>
            </div>
        </div>
    </div>

    <script language="JavaScript" type="text/javascript">

    var pagina="http://localhost:8000/factura/nueva"
    function redireccionar()
    {
    location.href=pagina
    }
        setTimeout ("redireccionar()", 0);

</script>


{% else %}
    <div class="row">
        <div class="col-lg-6">
            <div class="middle-box animated fadeInDown">
                <h2>Regístrate</h2>

                <form role="form" method="post" accept-charset="utf-8">
                    {% csrf_token %}

                    {% for field in user_register %}
                        <div class="form-group">
                            <!-- Render the field label tag -->
                                {{ field }}
                            <!--  muestra los errores que halla en los fields -->
                            {% if field.errors %}
                                <p class="error">
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                                </p>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="checkbox i-checks"><label> <input type="checkbox"><span class="m-l-sm">Acepto los términos y condiciones</span></label></div>
                    </div>
                    <button class="btn btn-primary m-b pull-right" id="btn-submit" type="submit" name="register_form">Registrate</button>
                </form>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="middle-box animated fadeInDown">
                <h2>Inicia Sesión</h2>
                <h5>{{ Error }}</h5>
                <form class="m-t" role="form" method="post" accept-charset="utf-8">
                    {% csrf_token %}

                    {% for field in login_form %}
                        <div class="form-group">
                            {% if field != login_form.recordarme %}
                                <!-- Render the field label tag -->
                                    {{ field }}
                                <!--  muestra los errores que halla en los fields -->
                                {% if field.errors %}
                                    <p class="error">
                                    {% for error in field.errors %}
                                        {{ error }}
                                    {% endfor %}
                                    </p>
                                {% endif %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="checkbox i-checks recuerdame"><label>{{ login_form.recordarme }}<span class="m-l-sm">Recuérdame</span></label></div>
                    </div>
                    <button class="btn btn-primary m-b pull-right" type="submit" name="login_form">Inicia Sesión</button>
                </form>

                <p>
                <a href="{% url 'reset_password_reset1' %}"><small>Forgot password?</small></a>
                </p>
                <!-- LINK PARA LOGUEARSE CON FB, 'FUNCIONANDO' ES FACEBOOK, faltan las llaves para poder con twitter y linkedin-->
                <!-- SI EL USUARIO ESTA LOGUEADO, LO SALUDA, SI NO, LO INVITA A LOGUEARSE CON FB, TWITTER O LINKEDIN-->
                <hr/>
            </div>
        </div>
    </div>

{% endif %}

{% endblock %}

{% block scripts %}

{% endblock %}

facturacion_electronica/templates/usuarios/perfil.html
{% extends 'base/base_no_sidebar.html' %}
{% load staticfiles %}

{% block title %}
Editar Perfil
{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Tu Perfil</h5>
                </div>
                <div>
                    <div class="ibox-content no-padding">
                         {% if user.get_image != "" %}
                        <img alt="image" class="img-responsive" src="{{ user.get_image }}">
                         {% else %}
                        <img alt="image"  src="{% static 'base/img/avatar.jpg' %}" style="height: 42px"/>
                         {% endif %}

                    </div>
                    <div class="ibox-content profile-content" >
                        <div id="div_usuario">
                            <h4><strong>{{ user.get_full_name }}</strong></h4>
                            <p>Desde: {{ user.fechaRegistro|date }}</p>
                            <p><i class="fa fa-map-marker"></i> {{ user.email }}</p>

                            <p>Fecha de nacimiento: {{ user.fechaNac|date }}</p>

                            <p>RFC: {{ user.rfc }}</p>
                        </div>
                        <div id="div_perfil">
                            <p>Telefono : {{ user.telefono }}</p>
                            <p>Direccion : {{ user.direccion }}</p>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <h3>Para hacer mas rapida y comoda tu gestion de facturas, te pedimos tu informacion
                personal,</h3>
            <form class="form-group" action="{% url 'usuarios_app:perfil' %}" method="post" enctype="multipart/form-data" id="form_datos">
                {% csrf_token %}
                {% for field in completar_perfil %}
                    <div class="form-group">
                        <!-- Render the field label tag -->
                        {{ field }}
                        <!--  muestra los errores que halla en los fields -->
                        {% if field.errors %}
                            <p class="error">
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                            </p>
                        {% endif %}
                    </div>
                {% endfor %}
                <button class="btn btn-primary m-b pull-right" id="btn-submit" type="submit" href="{% urk %}" >
                    Actualizar
                </button>
            </form>


        </div>
    </div>

{% endblock %}

{% block scripts %}
<script src="{% static 'base/js/plugins/summernote/summernote.min.js' %}"></script>

    <script>
    //div_cuenta
        $('#btn-cuenta').on('click', cuentas);
        function cuentas()
        {
            $.ajax
            ({
                data: $("#form_cuenta").serialize(),
                url: '/editar_ajax2/',
                type: 'post',
                success: function (result)
                {
                    result = jQuery.parseJSON(result.cuentas_usuario);
                    var html="";
                    for (var i=0 ;i<result.length;i++)
                    {
                        //html+= '<span>'+result[i].fields.url+'</span><br><span>'
                        //    +result[i].fields.tipo_red_social+'</span><br>'
                        html+='<span>Descripcion: '+result[i].fields.banco+'</span><br>'
                                +'<span>Numero :'+result[i].fields.numero_de_cuenta+'</span>'
                                + '<button id="Borrar" class="btn btn-primary  btn-xs" type="button">Borrar</button><br>'

                    }
                    ////console.log(html);
                    $('#div_cuenta').html(html);
                },
                error: function (result)
                {
                    alert("No contesta el servidor ");
                }
            });
        }
    </script>
{% endblock %}